### ISSUE TITLE
a library of prompts is missing (style)

### ISSUE THREAD

**Issue by yegor256** [horw/issue-title-ai#20]
It is rather inconvenient to create prompts in every repository. Would be nice to have an ability to just say (using `style` option):

```
- uses: horw/issue-title-ai@v0.1.2b
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    openai-api-key: ${{ secrets.OPENAI_API_KEY }}
    style: offensive-blame
```

Here, the `offensive-blame` means that we should use a pre-defined prompt, which turns all ticket titles into bugs, blaming the code base for errors.

Other possible styles:

- `polite-suggestion` - suggest an improvement, politely
- `task-order` - give an order
- `summarization` - make a summary of the problem
