### ISSUE TITLE
yamllint is not used

### ISSUE THREAD

**Issue by yegor256** [horw/issue-title-ai#28]
Since the directory has a few YAML files, it may be helpful to use YamlLint checker, as part of CI. See how we do it here: https://github.com/objectionary/lints/blob/master/.github/workflows/yamllint.yml

**Comment by horw** [comment]
I have used the following pre-commit YAML configuration instead:
```yaml
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.33.0
  hooks:
    - id: yamllint
      args: [--config-file=.yamllint.yml]
```

**Comment by yegor256** [comment]
@horw pre-commit doesn't guarantee that other users, in their pull requests, won't break YAML formatting

**Comment by horw** [comment]
> [@horw](https://github.com/horw) pre-commit doesn't guarantee that other users, in their pull requests, won't break YAML formatting


It's okay; I have a pre-commit job:
```
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
```
